# Generated by Django 4.1.13 on 2024-04-14 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0003_student_remove_user_role_user_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="course_files/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.teacher",
                    ),
                ),
            ],
        ),
    ]
